apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CodrinE/SampleGitOpsApp.git'
    path: pacman
    targetVersion: main
    helm:
      releaseName: pacman
      values: |
        replicaCount: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true